In [58]:
import gym
import random
import numpy as np
import matplotlib.pyplot as plt

In [59]:
env = gym.make("Pendulum-v1")

In [60]:
print(env.env.action_space)
print(env.env.action_space.high)
print(env.env.action_space.low)

Box(-2.0, 2.0, (1,), float32)
[2.]
[-2.]


In [61]:
print(env.env.observation_space)
print(env.env.observation_space.high)
print(env.env.observation_space.low)

Box([-1. -1. -8.], [1. 1. 8.], (3,), float32)
[1. 1. 8.]
[-1. -1. -8.]


In [62]:
theta_space = np.linspace(-1,1,10)
dot_space = np.linspace(-8,8,10)
act_space = np.linspace(-2,2,10)

In [63]:
def get_state(observation):
    cos, sin, dot = observation
    cth = int(np.digitize(cos,theta_space))
    sth = int(np.digitize(sin,theta_space))
    dth = int(np.digitize(dot,dot_space))
    return (cth + sth + dth)

In [64]:
def get_act(action):
    act = action
    ath = (np.digitize(act,act_space))
    ath = int(ath)
    return ath

In [65]:
rewa = []
pstate = []
pactions = []

In [66]:
obs = env.reset()
for i in range(1000):
    action = env.action_space.sample()
    staterun = get_state(obs)
    pstate.append(staterun)
    actrun = get_act(action)
    pactions.append(actrun)
    rewa.append(reward)
    obs, reward, done, info = env.step(action)

In [67]:
avgrewa=(sum(rewa)/len(rewa))
print(avgrewa)

-6.522399940023102


In [68]:
pstate = list(dict.fromkeys(pstate))
pstate.sort()
print(pstate)

[4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]


In [69]:
pactions = list(dict.fromkeys(pactions))
pactions.sort()
print(pactions)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [82]:
#Variables
states = pstate
actions = pactions
N_STATES = len(states)
N_ACTIONS = len(actions)
R = np.zeros((N_STATES, N_ACTIONS, N_STATES))
P = np.zeros((N_STATES, N_ACTIONS, N_STATES))
P.fill(0.001)
R.fill(avgrewa)
# The lowest reward is -(pi^2 + 0.1*8^2 + 0.001*2^2) = -16.2736044, and the highest reward is 0.
gamma = 0.1

In [83]:
for i in range(10000):
        x = random.uniform(-16.2736044,-0.99999)
        a = random.randint(1,20)
        b = random.randint(1,8)
        c = random.randint(1,20)
        R[a,b,c] = x

In [84]:
R

array([[[ -6.52239994,  -6.52239994,  -6.52239994, ...,  -6.52239994,
          -6.52239994,  -6.52239994],
        [ -6.52239994,  -6.52239994,  -6.52239994, ...,  -6.52239994,
          -6.52239994,  -6.52239994],
        [ -6.52239994,  -6.52239994,  -6.52239994, ...,  -6.52239994,
          -6.52239994,  -6.52239994],
        ...,
        [ -6.52239994,  -6.52239994,  -6.52239994, ...,  -6.52239994,
          -6.52239994,  -6.52239994],
        [ -6.52239994,  -6.52239994,  -6.52239994, ...,  -6.52239994,
          -6.52239994,  -6.52239994],
        [ -6.52239994,  -6.52239994,  -6.52239994, ...,  -6.52239994,
          -6.52239994,  -6.52239994]],

       [[ -6.52239994,  -6.52239994,  -6.52239994, ...,  -6.52239994,
          -6.52239994,  -6.52239994],
        [ -6.52239994, -11.28622795, -11.03511237, ...,  -4.5133438 ,
         -15.48646671,  -6.52239994],
        [ -6.52239994,  -5.25981845, -11.44216577, ..., -15.69996447,
          -3.65657484,  -6.13364582],
        ...,


In [85]:
# Policy Iteration
## Initialise
policy = [0 for s in range(N_STATES)]
V = np.zeros(N_STATES)

## Iterate
is_value_changed = True
iterations = 0
while is_value_changed:
    is_value_changed = False
    iterations += 1
    for s in range(N_STATES):
        V[s] = sum([P[s,policy[s],s1] * (R[s,policy[s],s1] + gamma * V[s1]) for s1 in range(N_STATES)])

## Evaluate
    for s in range(N_STATES):
        q_best = V[s]
        for a in range(N_ACTIONS):
            q_sa = sum([P[s, a, s1] * (R[s, a, s1] + gamma * V[s1]) for s1 in range(N_STATES)])
            if q_sa > q_best:
                print("State", s, ": q_sa", q_sa, "q_best", q_best)
                policy[s] = a
                q_best = q_sa
                is_value_changed = True

State 11 : q_sa -0.13654979736443382 q_best -0.1371211415354236
State 13 : q_sa -0.130092133484818 q_best -0.1371485671349421
State 18 : q_sa -0.1172059208006866 q_best -0.13721715513473784
State 0 : q_sa -0.13725584796561377 q_best -0.13725832439793012
State 1 : q_sa -0.13725584796561377 q_best -0.13725835319049587
State 2 : q_sa -0.13725584796561377 q_best -0.13725838061623688
State 3 : q_sa -0.13725584796561377 q_best -0.1372584066748795
State 4 : q_sa -0.13725584796561377 q_best -0.13725843136615007
State 5 : q_sa -0.13725584796561377 q_best -0.1372584546897748
State 6 : q_sa -0.13725584796561377 q_best -0.13725847664547994
State 7 : q_sa -0.13725584796561377 q_best -0.1372584972329917
State 8 : q_sa -0.13725584796561377 q_best -0.13725851645203618
State 9 : q_sa -0.13725584796561377 q_best -0.1372585343023395
State 10 : q_sa -0.13725584796561377 q_best -0.1372585507836277
State 11 : q_sa -0.1365473209321174 q_best -0.13655003886213052
State 12 : q_sa -0.13725584796561377 q_best -0

In [86]:
print(policy)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 2, 0, 0, 0, 0, 6, 0, 0]
